const NUMBER_PATTERN = '^[0-9.]*$';

const FAKE_CALCULATOR_ARRAY_MORE_THEN_TWO = [
  [19, 15, 0],
  [16, 42, 0],
  [0, 0, 0],
  [0, 0, 0],
  [15, 12, 0],
]

const FAKE_INVALID_CALCULATOR_ARRAY_MORE_THEN_TWO = [
  [-12, -45, 0],
  [-16,-42, 0],
  [0, 0, 0],
  [0, 0, 0],
  [-15, -12, 0],
]

const FAKE_CALCULATOR_AVERAGE_SUM = 16.789473684210527;

const FAKE_CALCULATOR_INPUT_NAMES_MORE_THEN_TWO = ['foo', 'bar', 'baz', 'qux', 'quux'];

export {
  NUMBER_PATTERN,
  FAKE_CALCULATOR_ARRAY_MORE_THEN_TWO,
  FAKE_CALCULATOR_INPUT_NAMES_MORE_THEN_TWO,
  FAKE_CALCULATOR_AVERAGE_SUM,
  FAKE_INVALID_CALCULATOR_ARRAY_MORE_THEN_TWO
};
